export const GENRES = [
  { name: "Comedy", url: "https://www.natomanga.com/genre/comedy" },
  {
    name: "Supernatural",
    url: "https://www.natomanga.com/genre/supernatural",
  },
  { name: "Drama", url: "https://www.natomanga.com/genre/drama" },
  { name: "Fantasy", url: "https://www.natomanga.com/genre/fantasy" },
  { name: "Action", url: "https://www.natomanga.com/genre/action" },
  { name: "Josei", url: "https://www.natomanga.com/genre/josei" },
  { name: "Adventure", url: "https://www.natomanga.com/genre/adventure" },
  { name: "Romance", url: "https://www.natomanga.com/genre/romance" },
  { name: "Smut", url: "https://www.natomanga.com/genre/smut" },
  { name: "Manhwa", url: "https://www.natomanga.com/genre/manhwa" },
  { name: "Tragedy", url: "https://www.natomanga.com/genre/tragedy" },
  {
    name: "Slice of life",
    url: "https://www.natomanga.com/genre/slice-of-life",
  },
  { name: "School life", url: "https://www.natomanga.com/genre/school-life" },
  { name: "Seinen", url: "https://www.natomanga.com/genre/seinen" },
  { name: "Historical", url: "https://www.natomanga.com/genre/historical" },
  { name: "Harem", url: "https://www.natomanga.com/genre/harem" },
  { name: "Horror", url: "https://www.natomanga.com/genre/horror" },
  {
    name: "Psychological",
    url: "https://www.natomanga.com/genre/psychological",
  },
  { name: "Mystery", url: "https://www.natomanga.com/genre/mystery" },
  { name: "Shounen", url: "https://www.natomanga.com/genre/shounen" },
  {
    name: "Martial arts",
    url: "https://www.natomanga.com/genre/martial-arts",
  },
  { name: "Manhua", url: "https://www.natomanga.com/genre/manhua" },
  { name: "Shoujo", url: "https://www.natomanga.com/genre/shoujo" },
  { name: "Isekai", url: "https://www.natomanga.com/genre/isekai" },
  {
    name: "Gender bender",
    url: "https://www.natomanga.com/genre/gender-bender",
  },
  { name: "Mature", url: "https://www.natomanga.com/genre/mature" },
  { name: "Webtoons", url: "https://www.natomanga.com/genre/webtoons" },
  { name: "Shoujo ai", url: "https://www.natomanga.com/genre/shoujo-ai" },
  { name: "Yaoi", url: "https://www.natomanga.com/genre/yaoi" },
  { name: "Yuri", url: "https://www.natomanga.com/genre/yuri" },
  { name: "Medical", url: "https://www.natomanga.com/genre/medical" },
  { name: "Mecha", url: "https://www.natomanga.com/genre/mecha" },
  { name: "Shounen ai", url: "https://www.natomanga.com/genre/shounen-ai" },
  { name: "Sports", url: "https://www.natomanga.com/genre/sports" },
  { name: "Cooking", url: "https://www.natomanga.com/genre/cooking" },
  { name: "Sci fi", url: "https://www.natomanga.com/genre/sci-fi" },
  { name: "One shot", url: "https://www.natomanga.com/genre/one-shot" },
  { name: "Ecchi", url: "https://www.natomanga.com/genre/ecchi" },
  { name: "Long Strip", url: "https://www.natomanga.com/genre/long-strip" },
  { name: "Survival", url: "https://www.natomanga.com/genre/survival" },
];
